### PR TITLE
Suck dai from the vow instead of the flash mint module to save gas

### PR DESCRIPTION
**Pull request by hexonaut**
My intuition is saying this will decrease gas as it no longer touches the sin and dai for the flash contract and deals directly in the vow. It also removes a `vat.move()` from both functions.

TODO - test the gas differences on Kovan.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
The reason why we avoided using the `vow` in the first place was because you could launch debt auctions in the middle.
Preventing launching flop auctions would require extra stuff that would kill the gas savings and would make the module more complex, so IMO we should leave it as it is.

**Comment by hexonaut** [comment]
I think actually it was just by accident I originally coded it to suck from the flash module, but yeah I guess the small gas savings aren't worth this last minute change. I'll leave this open for a future deploy if and when we get around to that.

**Comment by gbalabasquer** [comment]
I'm pretty sure we had discussed to not use the `vow` for this reason, but I might be wrong.
Regarding the gas optimizations, we should see if they actually exist. We should have a dependency to the `flop`, read from it the `kick`s in the beginning and at the end. Probably is a bit cheaper as we will avoid some `SSTORE` but the solution is not elegant at all. If we do async fees collection we could have the same gas optimizations.

**Comment by hexonaut** [comment]
Closing this as we are doing fees async now anyways.

**Pull request closed without merging**
